# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_artist_main_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='main_genre',
            field=models.CharField(max_length=50),
        ),
    ]
