# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20170419_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='main_genre',
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='history.Genre'),
            preserve_default=False,
        ),
    ]
